[build]
  command = "./netlify.sh"
  publish = "dist"
  
# Use our custom plugin to copy locale files
[[plugins]]
  package = "./netlify/copy-locales.js"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configure proper caching for assets and improve performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "public, no-cache"

[[headers]]
  for = "/locales/*"
  [headers.values]
    Cache-Control = "public, no-cache, must-revalidate" 