spring:
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_API_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

app:
  email:
    base-url: https://your-frontend-url.herokuapp.com 