spring:
  mail:
    host: smtp.mailgun.org
    port: 587
    username: ${MAILGUN_SMTP_USERNAME}
    password: ${MAILGUN_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false

app:
  email:
    from: ${MAILGUN_FROM_ADDRESS}
    base-url: https://clozet.netlify.app/
    verification-expiry-hours: 24
    password-reset-expiry-hours: 1

  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000
    cookie-max-age: 3600
    refresh-expiration: 604800000  # 7 days in milliseconds
    refresh-cookie-max-age: 604800  # 7 days in seconds
    secure-cookie: true

  upload:
    dir: uploads

  storage:
    use-cloudinary: true

  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
