spring:
  mail:
    host: smtp.mailgun.org
    port: 587
    username: ${MAILGUN_SMTP_USERNAME}
    password: ${MAILGUN_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
   
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false

app:
  email:
    from: ${MAILGUN_FROM_ADDRESS}
    base-url: ${APP_BASE_URL:https://clozet.netlify.app/}
    verification-expiry-hours: 24
    password-reset-expiry-hours: 1

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:3600000}
    cookie-max-age: ${JWT_COOKIE_MAX_AGE:3600}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}
    refresh-cookie-max-age: ${JWT_REFRESH_COOKIE_MAX_AGE:604800}
    secure-cookie: ${JWT_SECURE_COOKIE:true}

  upload:
    dir: ${UPLOAD_DIR:uploads}

  storage:
    use-cloudinary: ${USE_CLOUDINARY:true}

  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}