spring:
  profiles:
    active: dev
  mail:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Application-specific settings
app:
  email:
    from: noreply@clozet.com
    verification-expiry-hours: 24
    password-reset-expiry-hours: 1
    base-url: http://localhost:5173
  upload:
    dir: uploads
  storage:
    use-cloudinary: true
  cloudinary:
    cloud-name: dmoe4eqt4
    api-key: 298875699675921
    api-secret: 1kAWETGi8leIYAugHlCtvH7rBAg

logging:
  level:
    org.springframework.mail: DEBUG
    com.cloudinary: DEBUG