spring:
  profiles:
    active: dev
  application:
    name: backend
  datasource:
    url: jdbc:h2:file:./data/clozet;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  mail:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:3600000}
    cookie-max-age: ${JWT_COOKIE_MAX_AGE:3600}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}
    refresh-cookie-max-age: ${JWT_REFRESH_COOKIE_MAX_AGE:604800}
    secure-cookie: ${JWT_SECURE_COOKIE:false}
  email:
    from: ${MAILGUN_FROM_ADDRESS:noreply@clozet.com}
    verification-expiry-hours: 24
    password-reset-expiry-hours: 1
    base-url: ${APP_BASE_URL:https://clozet.netlify.app}
  upload:
    dir: ${UPLOAD_DIR:uploads}
  storage:
    use-cloudinary: ${USE_CLOUDINARY:false}

logging:
  level:
    org.springframework.mail: DEBUG
    com.cloudinary: DEBUG