spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false

  mail:
    enabled: false
    host: smtp.mailgun.org
    port: 587
    username: postmaster@sandbox25f0009567d5425391596f541e2cc221.mailgun.org
    password: b8f0a713a60cbab4a3d9179e0a488b59-24bda9c7-34dc91a8
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${PORT:8080}

app:
  email:
    from: postmaster@sandbox25f0009567d5425391596f541e2cc221.mailgun.org
    base-url: https://clozet.netlify.app/
    verification-expiry-hours: 24
    password-reset-expiry-hours: 1
  upload:
    dir: uploads
  storage:
    use-cloudinary: true
  cloudinary:
    cloud-name: dmoe4eqt4
    api-key: 298875699675921
    api-secret: 1kAWETGi8leIYAugHlCtvH7rBAg

logging:
  level:
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.boot: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: INFO
    stud.ntnu.no.backend: DEBUG
