name: Backend CI/CD

on:
  push:
    branches:
      - develop
      - main
      - 'feature/**'
    pull_request:
      branches:
        - develop
        - main
jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Set up Java
        - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
        - name: Build with Maven
          run: mvn clean compile
