name: Backend CI/CD

on:
  push:
    branches:
      - develop
      - main
      - 'feature/**'
  pull_request:
    branches:
      - develop
      - main


jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean compile

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    needs: build-backend
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run tests
        run: mvn test
      - name: Upload test results
        uses: actions/upload-artifact@v4.6.2
        with:
          name: surefire-reports
          path: backend/target/surefire-reports/
  
  package-backend:
    name: Package Backend
    runs-on: ubuntu-latest
    needs: test-backend
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Package JAR
        run: mvn package -DskipTests
      - name: Upload JAR
        uses: actions/upload-artifact@v4.6.2
        with:
          name: spring-boot-jar
          path: backend/target/*.jar

  deploy-backend:
    name: Deploy Backend to Heroku
    runs-on: ubuntu-latest
    needs: package-backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Backend
        working-directory: backend
        run: mvn clean install -DskipTests

      - name: Prepare Heroku Deploy Folder
        run: |
          mkdir deploy
          cp backend/target/*.jar deploy/app.jar
          echo "web: java -Dserver.port=\$PORT -jar app.jar" > deploy/Procfile

      - name: Set up Git and Push to Heroku
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          export PATH="$PATH:/app/.heroku/bin"
          heroku auth:token
          heroku buildpacks:clear -a ${{ secrets.HEROKU_APP_NAME }}
          heroku buildpacks:set heroku/java -a ${{ secrets.HEROKU_APP_NAME }}
          cd deploy
          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote add heroku https://heroku:${{ secrets.HEROKU
