name: Frontend CI/CD

on:
  push:
    branches: 
      - develop
      - main
      - 'feature/**'
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4.3.0
        with: 
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        run: npm install
      - name: Format code
        run: npm run format
      - name: Build frontend
        run: npm run build
      - name: Upload dist
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: vue-dist
          path: frontend/dist/

  test-frontend:
    name: Test Frontend (Unit + E2E)
    runs-on: ubuntu-latest
    needs: build-frontend
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4.3.0
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        run: npm run build
      - name: Run unit tests
        run: npm run test:unit
      - name: Upload coverage
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: frontend-coverage
          path: frontend/coverage/
    # Add cypress testing
      
